---
openapi: 3.0.3
info:
  title: Widget API
  description: |
    This is a sample server for a widget API, built with Rails and the Committee 
    gem for working with OpenAPI.
  version: "1.0.0"

servers:
- description: 'Production'
  url: 'https://example.com'

paths:
  "/widgets":
    get:
      summary: List widgets
      description: |
        This endpoint returns a list of widgets.
      operationId: list-widgets
      parameters: []
      responses:
        '200':
          description: successful
          headers:
            Cache-Control:
              schema:
                type: string
              description: This header declares the cacheability of the content so
                you can skip repeating requests.
          content:
            application/json:
              examples:
                example_key:
                  value:
                  - id: 1
                    title: Goblin Staff of Sparks
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: 123e4567-e89b-12d3-a456-426614174000
                        title:
                          type: string
                          example: Goblin Staff of Sparks
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
        '429':
          description: too many requests
          headers:
            X-Rate-Limit-Limit:
              schema:
                type: integer
              description: The number of allowed requests in the current period
            X-Rate-Limit-Remaining:
              schema:
                type: integer
              description: The number of remaining requests in the current period
            X-Rate-Limit-Reset:
              schema:
                type: integer
              description: The number of seconds left in the current period
    post:
      summary: create widget
      responses:
        '200':
          description: successful
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        detail:
                          type: string
                        code:
                          type: string
  "/widgets/{id}":
    parameters:
    - name: id
      in: path
      description: The unique identifier of a widget.
      required: true
      schema:
        type: string
    get:
      summary: show widget
      responses:
        '200':
          description: successful
    put:
      summary: update widget
      responses:
        '200':
          description: successful
