
name: Check & deploy API documentation
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      
      - name: Install dependencies
        run: bundle install
      
      - name: Generate OpenAPI
        run: bundle exec rake rswag

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: rails-hello-openapi
          token: ${{secrets.BUMP_TOKEN}}
          file: api/openapi.yaml

  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      
      - name: Install dependencies
        run: bundle install

      - name: Generate OpenAPI
        run: bundle exec rake rswag

      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: rails-hello-openapi
          token: ${{secrets.BUMP_TOKEN}}
          file: api/openapi.yaml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


    